steps:
  - label: ":percy::hamster: test"
    command: "make build && make test"
    timeout: 20

  - wait: ~
   continue_on_failure: true

  - label: ":junit:"
    commands:
      - .buildkite/junit.sh
